[package]
name = "libc-unix-shim"
version = "0.1.0"
authors = ["Gero Posmyk-Leinemann <gero.posmyk-leinemann@typefox.io>"]
edition = "2018"

[lib]
name = "libc_unix_shim"
path = "src/lib.rs"

[[bin]]
name = "libc_test"
path = "src/main.rs"

[dependencies]
syscall = "0.2.1"
